### ISSUE TITLE
Create the homepage

### ISSUE THREAD

**Issue by janKozie1** [janKozie1/projekt_zespolowy#14]
https://xd.adobe.com/view/d3ecb8e8-1d08-42a3-888e-e2f52ed69318-86bf/specs/

**Comment by Skydem** [comment]
https://www.pexels.com/pl-pl/zdjecie/uprawa-zadowolona-kobiete-z-pudelkiem-suszonych-kwiatow-opuszcza-kwiaciarnie-5414059/
