### ISSUE TITLE
Design an exemplary view of the app

### ISSUE THREAD

**Issue by janKozie1** [janKozie1/projekt_zespolowy#4]
- pick a component library for designing the app
 - design a view that frontend could use to set up their component library

**Comment by Skydem** [comment]
Library used: https://m2.material.io/resources/

**Comment by Skydem** [comment]
https://xd.adobe.com/view/1bf6e2d5-e440-40e4-8621-296aa0a98b19-4ea5/

**Comment by Skydem** [comment]
Link update, old one stopped working.
Assets such as images can be downloaded directly from this page.
https://xd.adobe.com/view/6c31b28a-b8d9-4fef-b0df-f130a5207e4c-3962/
