### ISSUE TITLE
Allow user to get their dashboard data

### ISSUE THREAD

**Issue by janKozie1** [janKozie1/projekt_zespolowy#43]
user should be able to get their dashboard data, example here
https://xd.adobe.com/view/1bf6e2d5-e440-40e4-8621-296aa0a98b19-4ea5/screen/96ed1e6b-ae57-4822-b84f-ee666fc976d9/specs/

**Comment by wsliwa** [comment]
I created two endpoints:

- /api/gift-discover/

Returns list of gift data for 3 random gifts. Created for "Odkywaj" section.

`[
  {
    "id": 0,
    "name": "string",
    "price": 0,
    "store_id": 0,
    "picture": "string"
  }
]`

- /api/incoming-gifts/{id}/

Where id is an user id. Returns list of data from table shoppingcart joined with userevents table. Only shows events in upcoming 90 days, ordered by event date and limited to 10 records.

Created for "Nadchodzące" section.


Created pull request #63
