### ISSUE TITLE
Allow users to invite & accept friend request

### ISSUE THREAD

**Issue by janKozie1** [janKozie1/projekt_zespolowy#57]
needs to extend DB schema (not included in #7)

https://github.com/janKozie1/projekt_zespolowy/blob/6970c530a9f0f026bfa460e435e06e7be062d0a4/frontend/src/services/api/types/index.ts#L56

https://github.com/janKozie1/projekt_zespolowy/blob/6970c530a9f0f026bfa460e435e06e7be062d0a4/frontend/src/services/api/types/data.ts#L11

![image](https://user-images.githubusercontent.com/48291123/209866443-2d7b9e1b-aa1c-4818-a864-f021a0ce1140.png)
![image](https://user-images.githubusercontent.com/48291123/209866475-c3059496-6217-4df1-b849-8995addc7d79.png)
![image](https://user-images.githubusercontent.com/48291123/209866494-4d883d2a-caff-47ea-848c-29b75e4806b6.png)

**Comment by wsliwa** [comment]
Pull request #77

To database added new table for friend requests and friend listing as shown below:
![image](https://user-images.githubusercontent.com/94856001/211144754-bfa12ad0-aa38-4a43-8f76-8f77434ad950.png)

- To create friend request:

POST /api/friend/
with data:
```
{
  "user": 1,
  "friend": 2,
  "status": "pending"
}
```
It will create firend request for user with id 2.

- To update friend request:

PUT /api/friend/{id}/

Id is a friend request id. Data needed to be send is for example:
```
{
  "status": "rejected"
}
```
Status can be either chaned to rejected or accepted.

(Friend request listing will be done in this issue: #72)

- To delete friend request:

DELETE /api/friend/{id}/

Id is a friend request id.


To list friends:
GET /api/user-friend-list/{id}/

Id is an user id. Endpoint returns list of friends with thier user data
