### ISSUE TITLE
Design DB schema

### ISSUE THREAD

**Issue by janKozie1** [janKozie1/projekt_zespolowy#7]
https://docs.google.com/document/d/10jrJuQV7ED7HviZ_EIAXm6odBaCjugUJ0j1leznReiU/edit#heading=h.6lzdhhnh7cwj

**Comment by wsliwa** [comment]
Link do schematu bazy danych:
https://dbdiagram.io/d/63910730bae3ed7c454571ce

Wersja 0:
![image](https://user-images.githubusercontent.com/94856001/206307189-aa9d7448-fde4-4edf-88f1-e0db6b38bdc4.png)

**Comment by janKozie1** [comment]
- zakładamy, że dany koszyk ma być dostarczony na jedną, konkretną datę, do jednej konkretnej osoby (a nie każdy produkt osobno)
- predefinowane kategorie eventów (użytkownicy mogą tworzyć wlaśne eventy ale nie ich kategorie)
- mapowanie kategorii eventu na kategorię prezentu
- spróbować połączyć koszyki z eventami a nie użytkownikami

**Comment by wsliwa** [comment]
Update bazy danych (link bez zmian).

Zmieniłem, tak jak ustalaliśmy na spotkaniu (zgodnie z komentarzem powyżej).

![image](https://user-images.githubusercontent.com/94856001/206859256-6d2f4176-ee5a-4846-8e95-f952a7850caa.png)

PROPOZYCJA ZMIANY:

Czy nie lepiej będzie zmienić w tabeli orders z relacji do tabeli gifts, na relację do tabeli shopping_cart?

**Comment by wsliwa** [comment]
Ostateczny schemat bazy danych:

![image](https://user-images.githubusercontent.com/94856001/207984949-358a2c3e-8fdd-4feb-8678-73085cae191d.png)

https://dbdiagram.io/d/63910730bae3ed7c454571ce
